---
- name: Basic Server Setup
  hosts: servers
  become: yes
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Purge basic packages
      apt:
        name:
          - curl
          - vim
          - git
        state: purged
