---
- name: Install Git and copy test file
  hosts: all
  become: yes
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Copy test file to remote host
      copy:
        src: /tmp/test-file.txt
        dest: /tmp/test-file.txt
        mode: '0644'

    - name: Clone Git repository
      git:
        repo: https://github.com/nirvxnx/my_docker_project.git
        dest: /root
