---
- name: Setup Nginx with Basic Authentication
  hosts: 147.45.71.93  # Замените на вашу группу хостов или 'localhost' для локальной настройки
  become: yes  # Выполнение с привилегиями root

  vars:
    htpasswd_file: /etc/nginx/.htpasswd
    nginx_user: "testuser"
  vars_files:
    - secrets.yml
  
  tasks:
    - name: Update apt cache and install necessary packages
      apt:
        update_cache: yes
        name:
          - nginx
          - apache2-utils
        state: present

    - name: Create htpasswd file with user and password
      command: htpasswd -cb {{ htpasswd_file }} {{ nginx_user }} {{ nginx_password }}
      args:
        creates: "{{ htpasswd_file }}"

    - name: Copy default file nginx configuration.
      copy:  
        src: files/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
