---
- name: Setup Nginx with Basic Authentication
  hosts: 147.45.41.53  # Замените на вашу группу хостов или 'localhost' для локальной настройки
  become: yes  # Выполнение с привилегиями root

  vars:
    htpasswd_file: /etc/nginx/.htpasswd
    nginx_user: "testuser"
    nginx_password: "testpassword"  # В реальном сценарии лучше зашифровать этот пароль

  tasks:
    - name: Update apt cache and install necessary packages
      apt:
        update_cache: yes
        name:
          - nginx
          - apache2-utils
        state: present

    - name: Create htpasswd file with user and password
      command: htpasswd -cb {{ htpasswd_file }} {{ nginx_user }} {{ nginx_password }}
      args:
        creates: "{{ htpasswd_file }}"

    - name: Configure Nginx for basic authentication
      blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          location /secure {
              auth_basic "Restricted Content";
              auth_basic_user_file {{ htpasswd_file }};
          }
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
