---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Deploy custom pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/16/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0640'
  notify: Restart postgresql
