---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes
